IF NOT EXISTS (SELECT 1 FROM sys.databases WHERE name = 'websystemdb')
BEGIN
	CREATE DATABASE websystemdb;
END;

USE websystemdb;

IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'CATEGORY')
BEGIN
	CREATE TABLE CATEGORY
	(
		ID_CATEGORY INT IDENTITY(1,1),
		ALIAS VARCHAR(50) NOT NULL
		PRIMARY KEY (ID_CATEGORY)
	);
END;

INSERT INTO CATEGORY VALUES ('Porcelanato');
INSERT INTO CATEGORY VALUES ('Inodoro');
INSERT INTO CATEGORY VALUES ('Lavadero');
INSERT INTO CATEGORY VALUES ('Accesorios');

IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'PRODUCT')
BEGIN
	CREATE TABLE PRODUCT
	(
		ID_PRODUCT INT IDENTITY(1,1),
		ID_CATEGORY INT,
		NAME_LARGE VARCHAR(100) NOT NULL,
		QUANTITY SMALLINT,
		UNIT_PRICE NUMERIC(6,2)
		PRIMARY KEY (ID_PRODUCT),
		CONSTRAINT FK_CATEGORY FOREIGN KEY (ID_CATEGORY) REFERENCES CATEGORY (ID_CATEGORY)
	);
END;

INSERT INTO PRODUCT 
VALUES (1,'Glazed',110,30.50),
(1,'Polished',250,60.52),
(1,'Double Charged',310,90.30),
(1,'Full Body',650,100.40),
(1,'Textured or Stone Finish',901,120.90),
(2,'Kohler',20,120.0),
(2,'American Standard',50,70.50),
(2,'Glacier Bay',10,90.0),
(2,'Delta',15,89.50),
(2,'Swiss Madison',12,99.99),
(3,'Houzer',25,50.99),
(3,'Elkay',20,80.99),
(3,'MR Direct',30,60.99),
(3,'Kraus',15,99.99),
(3,'Allora',70,76.99),
(4,'Italgrif',20,15.99);

IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'USER_TABLE')
BEGIN
	CREATE TABLE USER_TABLE
	(
		ID_USER INT IDENTITY(1,1),
		USERNAME VARCHAR(20) NOT NULL,
		PASSWORD VARCHAR(255) NOT NULL,
		USER_ROLE VARCHAR(20),
		ENABLED BIT DEFAULT 1

		PRIMARY KEY (ID_USER)

	);
END;

-- Borrar luego
INSERT INTO USER_TABLE VALUES ('admin','$2a$10$aiIZ3V.QS0AxIz4cQBoQE.doIYg/mDHXVXIZ2kJvuZtWopn5Siv8q','ADMIN',1);

IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'EMPLOYEE')
BEGIN
	CREATE TABLE EMPLOYEE
	(
		ID_EMPLOYEE INT IDENTITY(1,1),
		ID_USER INT,
		EMAIL VARCHAR(50),
		NAMES VARCHAR(100) NOT NULL,
		LASTNAME VARCHAR(100) NOT NULL,
		ADDRESS VARCHAR(200)

		PRIMARY KEY (ID_EMPLOYEE),
		CONSTRAINT FK_USER FOREIGN KEY (ID_USER) REFERENCES USER_TABLE (ID_USER)
	);
END;

INSERT INTO EMPLOYEE VALUES (1,'adminprueba@gmail.com','ULI', 'COS O', 'SMP');

IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'SUPPLIER')
BEGIN
	CREATE TABLE SUPPLIER
	(
		ID_SUPPLIER INT IDENTITY(1,1),
		DESCRIPTION_NAME VARCHAR(50) NOT NULL,
		CONTACT_NUMBER VARCHAR(20) NOT NULL,
		EMAIL VARCHAR(50),
		ADDRESS VARCHAR(200)

		PRIMARY KEY (ID_SUPPLIER)
	);
END;

INSERT INTO SUPPLIER (DESCRIPTION_NAME,CONTACT_NUMBER,EMAIL,ADDRESS) 
VALUES ('CELIMA','348594093','celima@corp.pe','SMP'),
('CHEMA','399297753','chema@corp.pe','SMP');

IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'SALES')
BEGIN
	CREATE TABLE SALES
	(
		ID_SALES VARCHAR(20),
		ID_EMPLOYEE INT,
		DATE_SALE DATE NOT NULL,
		CLIENT_SURNAME VARCHAR(100),
		CLIENT_CONTACT_NUMBER VARCHAR(20),
		IGV DECIMAL(3,2)

		PRIMARY KEY (ID_SALES),
		CONSTRAINT FK_EMPLOYEE FOREIGN KEY (ID_EMPLOYEE) REFERENCES EMPLOYEE (ID_EMPLOYEE)
	);
END;

IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'SALES_DETAILS')
BEGIN
	CREATE TABLE SALE_DETAILS
	(
		ID_SALE_DETAILS INT IDENTITY(1,1),
		ID_SALES VARCHAR(20),
		ID_PRODUCT INT NOT NULL,
		REQUIRED_QUANTITY SMALLINT,
		PRIMARY KEY (ID_SALE_DETAILS),
		CONSTRAINT FK_SALES FOREIGN KEY (ID_SALES) REFERENCES SALES (ID_SALES),
		CONSTRAINT FK_PRODUCT FOREIGN KEY (ID_PRODUCT) REFERENCES PRODUCT (ID_PRODUCT)
	);
END;